package dev.xtrafe.javai.e2e;

import dev.xtrafe.javai.e2e.domain.Tag;
import dev.xtrafe.javai.e2e.environment.JavAIEnvironment;
import dev.xtrafe.javai.model.JavAIVectorizable;
import dev.xtrafe.javai.vector.EmbeddingVector;
import dev.xtrafe.javai.vector.JavAIDirtyTracking;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Real end-to-end proof (not hermetic -- real embeddings from the live container, same as
 * {@code ArticleGraphEmbeddingE2ETest}) that Lombok and {@code javai-substrate}'s load-time weaver genuinely
 * coexist on the same class. The interesting claim isn't "both compile" -- it's that the specific mechanism
 * {@code JavAIWeaver} depends on (a conventionally-named {@code setXxx} method with real bytecode to attach
 * {@code Advice} to, and a constructor {@code ConstructorExitAdvice} can instrument) still holds when that
 * bytecode is Lombok-generated rather than hand-written. See {@link Tag}'s own javadoc for why the ordering
 * this was asked to prove (JavAI weaves only after Lombok is completely done) can never race in this build.
 *
 * <p>The weaver itself is installed by {@link JavAIWeavingLauncherSessionListener}, not here.
 */
class LombokInteropE2ETest {

    @BeforeAll
    static void configureRealProvider() {
        JavAIEnvironment.ensureRunning();
    }

    @Test
    void lombokGeneratedAccessorsWorkAlongsideWovenVectorization() {
        Tag tag = new Tag(UUID.randomUUID(), "zero-day");

        // Lombok's own generated methods behave normally -- unaffected by the weaver adding a further
        // private transient field and two more interfaces to the same class after Lombok is done with it.
        assertEquals("zero-day", tag.getLabel());
        assertTrue(tag.toString().contains("zero-day"));

        // The weaver's own contract: this class genuinely implements both interfaces at runtime, even
        // though nothing in Tag.java says `implements`.
        assertInstanceOf(JavAIVectorizable.class, tag);
        assertInstanceOf(JavAIDirtyTracking.class, tag);

        JavAIDirtyTracking dirtyTracking = (JavAIDirtyTracking) tag;
        JavAIVectorizable vectorizable = (JavAIVectorizable) tag;

        // Real, freshly computed embedding through the live container -- not a fake provider.
        EmbeddingVector first = vectorizable.vector();
        assertNotNull(first);
        assertTrue(first.dims() > 0);
        // vector() itself never clears FieldDirty -- it's deliberately uncached at this level (each
        // @Vectorize field caches independently via its own VectorCacheSlot; see JavAIRuntime.vector()'s
        // own javadoc), so there's no single object-level cache left for it to gate on. Establish a
        // known-clean baseline directly through the interface instead, so the assertion below actually
        // proves Lombok's setter is what marks it dirty, not just that the flag was never cleared at all.
        dirtyTracking.clearFieldDirty();

        // The point of this test: Tag.setLabel(String) is entirely Lombok-generated -- @Setter never wrote
        // a single line of this method's bytecode by hand. VectorizeFieldSetterAdvice must still be the
        // one attached to it, so calling it marks the field dirty and a subsequent vector() call recomputes.
        tag.setLabel("supply chain attack");
        assertTrue(dirtyTracking.isFieldDirty(), "Lombok's own setLabel(String) must trigger woven dirty-tracking");

        EmbeddingVector second = vectorizable.vector();
        assertFalse(Arrays.equals(first.values(), second.values()),
                "changing the vectorized field through Lombok's setter must produce a genuinely different embedding");
    }

    @Test
    void constructionThroughALombokGeneratedConstructorStillWiresDependencies() {
        // ConstructorExitAdvice attaches to every constructor found on the woven class, including this
        // one -- entirely generated by @AllArgsConstructor, never hand-written. Tag has no graph-shaped
        // fields to assert dependents on, so a construction that doesn't throw, followed by a working
        // vector() call, is the observable proof the advice ran correctly against Lombok's bytecode.
        Tag tag = new Tag(UUID.randomUUID(), "no-op proof");
        assertDoesNotThrow(() -> ((JavAIVectorizable) tag).vector());
    }
}
